{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}
  {{- include "base-app.labels" . | nindent 2 }}
  {{- with .Values.externalSecrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "60s" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind | default "SecretStore" }}
  target:
    name: {{ .Values.externalSecrets.targetSecret.name | default (include "app.fullname" .) }}
    {{- with .Values.externalSecrets.targetSecret.creationPolicy }}
    creationPolicy: {{ . }}
    {{- end }}
    {{- with .Values.externalSecrets.targetSecret.deletionPolicy }}
    deletionPolicy: {{ . }}
    {{- end }}
  
  {{- if .Values.externalSecrets.dataFrom }}
  {{/* Case 1: dataFrom - Load all keys from a path */}}
  dataFrom:
  {{- range .Values.externalSecrets.dataFrom }}
    - extract:
        key: {{ .key }}
        {{- with .version }}
        version: {{ . }}
        {{- end }}
        {{- with .property }}
        property: {{ . }}
        {{- end }}
      {{- with .find }}
      find:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .rewrite }}
      rewrite:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
  {{- end }}

  {{- if .Values.externalSecrets.data }}
  {{/* Case 2: data - Maps specific keys */}}
  data:
  {{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- with .remoteRef.property }}
        property: {{ . }}
        {{- end }}
        {{- with .remoteRef.version }}
        version: {{ . }}
        {{- end }}
      {{- with .sourceRef }}
      sourceRef:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
  {{- end }}
{{- end }}