# nameOverride -- name of the chart/release to override 'base-app' with
nameOverride:

##
# Pods configuration
##

pods:
  # pods.controller -- controller used to schedule pods
  # Can either be 'deployment', 'statefulset' or 'daemonset'
  controller: deployment
  
  # Container image to use
  image:
    # pods.image.name -- image repository/name
    name:

    # pods.image.tag -- image tag
    tag:

    # pods.image.pullPolicy -- image pullPolicy
    pullPolicy: IfNotPresent

    # pods.image.pullSecrets -- Optional array of imagePullSecrets containing private registry credentials
    # Ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    pullSecrets: []
    # - name: secretName

    # pods.image.pullCredentials -- Automatically create a secret with the credentials and use it
    # Cannot be used in conjunction of image.pullSecrets
    pullCredentials: {}
      # registry: quay.io
      # username: someone
      # password: sillyness

  # pods.replicas -- amount of desired pod(s) replica(s)
  # Ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#replicas
  replicas:

  # Specify revisionHistoryLimit (deployments only)
  # Ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy
  revisionHistoryLimit: 3

  # The update strategy to apply for the deployment, statefulset or daemonset
  ##
  strategy:
   rollingUpdate:
     maxUnavailable: 1
   type: RollingUpdate

  # Custom command to use for the container
  command: []

  # Custom arguments to use for the container
  args: []

  # Additional labels and annotations for the deployment, statefulset or daemonset
  labels: {}
  #  key: value
  annotations: {}
  #  key: value

  # Additional labels and annotations for the pods
  podLabels: {}
  #  key: value
  podAnnotations: {}
  #  key: value

  # Healthcheck probes
  livenessProbe: {}
  readinessProbe: {}

  # Resources allocation for the containers
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 512Mi
    # requests:
    #   cpu: 500m
    #   memory: 512Mi

  ports:
    - containerPort: 8080

  # Node labels for pod assignment
  # Ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  ## Node tolerations for server scheduling to nodes with taints
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  ##
  tolerations: []
  #  - key: "key"
  #    operator: "Equal|Exists"
  #    value: "value"
  #    effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

  # DNS Policy
  dnsPolicy: ClusterFirst

  # Affinity configuration
  affinity:
    # This allows you to automatically define anti-affinity rules
    antiAffinity:
      enabled: false
      type: hard  # Can be either 'hard' or 'soft'
      topologyKey: kubernetes.io/hostname

    rules: {}
  
  # Environment variables
  env: []
    # - name: key
    #   value: val
    # - name: other_key
    #    valueFrom:
    #      configMapKeyRef:
    #        name: config
    #        key: nice-key

  envFrom: []
    # - configMapRef:
    #     name: config
    # - secretRef:
    #     name: config

  # Volumes and mounts
  volumes: []
    # - name: storage
    #   emptyDir: {}

  volumeMounts: []
    # - name: storage
    #   mountPath: /mnt/storage

  # Security
  securityContext: {}

  # Init containers configuration
  initContainers: []

  # Additional containers for the pods
  additionalContainers: []

##
# Image Pull Credentials
##

# Automatically create a secret with the credentials and use it
# Cannot be used in conjunction of pods.imagePullSecrets
imageCredentials: {}
  # registry: quay.io
  # username: someone
  # password: sillyness

##
# Horizontal Pod Autoscaler configuration
##

# Create HorizontalPodAutoscaler, only works for 'deployments' and 'statefulsets'
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 15
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 20
          periodSeconds: 60

##
# Create HorizontalPodAutoscaler with keda, only works for 'deployments'
##

scaling:
  enabled: false
  pollingInterval: 30 # Intervalo de tempo em segundos para scaling
  cooldownPeriod: 60  # Intervalo de tempo em segundos para downscaling a partir do processamento da última mensagem (ou ação do trigger em questão)
  minReplicas: 1
  maxReplicas: 10
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "80"
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 15
          policies:
            - type: Percent
              value: 10
              periodSeconds: 60
        scaleDown:
          stabilizationWindowSeconds: 30
          policies:
            - type: Percent
              value: 20
              periodSeconds: 60

##
# Service configuration
##

service:
  enabled: false
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http

serviceHeadless:
  enabled: false
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
    
##
# Ingress configuration
##

ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

  path: /
  pathType: Prefix

  ingressClassName: "nginx"

  service:
    port:
      name: http

  hosts: []
    # - example.com
  tls: []
    # - hosts:
    #     - example.com

##
# Pod Disruption Budget configuration
##

podDisruptionBudget:
  enabled: false
  minAvailable: 1

##
# ConfigMaps management
##

configMaps: {}
  # foo:
  #   FOO: bar

##
# Secrets management
##

secrets: {}
  # super_secret:
  #   key: sensitive_value
  # dockerconfigjson/image-pull: |
  #   .dockerconfigjson: {}

##
# Service account management
##

serviceAccount:
  # serviceAccount.create -- create a service account and associate it with the pods
  create: false

  # serviceAccount.name -- name of the service account to use (and potentially create)
  name: default

##
# Service monitor configuration
##

serviceMonitor:
  enabled: false
  interval: 30s
  port: metrics
  path: /metrics

##
# Datadog specific env variables and labels
##

datadog:
  # global.datadog.enabled -- inject datadog related labels/env variables
  enabled: false

  # global.datadog.env -- current environment
  # env: (default to unknown)

  # global.datadog.service -- app/service name
  # service: (default to release name)

  # global.datadog.version -- app version
  # version: (default to appVersion + release revision)

##
# Global configuration (ideal when embedding this chart within another)
##

global:
  ##
  # Datadog specific env variables and labels
  ##

  datadog:
    # global.datadog.enabled -- inject datadog related labels/env variables
    enabled: false

    # global.datadog.env -- current environment
    # env: (default to unknown)

    # global.datadog.service -- app/service name
    # service: (default to release name)

    # global.datadog.version -- app version
    # version: (default to appVersion + release revision)

##
# Argo Rollouts configuration
##

# This new section controls the generation of a Rollout object.
# If 'enabled' is true, the 'deployment.yaml' template will generate a 'kind: Rollout'.
rollout:
  enabled: false

  # Defines the deployment strategy. You can use either 'canary' or 'blueGreen'.
  # Uncomment the strategy you want to use.
  strategy:
    # Example for Canary strategy.
    # Ref: https://argo-rollouts.readthedocs.io/en/stable/features/canary/
    canary:
      # Defines the canary deployment steps.
      steps:
      # 1. Sends 20% of the traffic to the new version.
      - setWeight: 20
      # 2. Pauses the rollout. Promotion to the next step must be done
      #    manually (or via automation, with 'opsmaster argocd app rollout promote').
      - pause: {}
      # 3. After manual promotion, sends 50% of the traffic.
      - setWeight: 50
      # 4. Pauses again for 1 minute before automatically promoting to 100%.
      - pause:
          duration: 1m
    
    # Example for Blue/Green strategy.
    # Ref: https://argo-rollouts.readthedocs.io/en/stable/features/bluegreen/
    # blueGreen:
    #   # The service that is actively serving production traffic.
    #   activeService: my-service-active
    #   # The service that is receiving the new version for testing.
    #   previewService: my-service-preview
    #   # After the new version is ready, the rollout will pause before switching traffic.
    #   autoPromotionEnabled: false