---
name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Push Helm chart to OCI compatible registry (Github)
        uses: bsord/helm-push@v4.2.0
        with:
          force: true
          useOCIRegistry: true
          username: ${GITHUB_ACTOR}
          chart-folder: charts/generic-app
          access-token: ${{ secrets.GITHUB_TOKEN }}
          registry-url:  oci://ghcr.io/${{ github.repository }}
