---
name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # - name: Set up Helm
      #   uses: azure/setup-helm@v4
      #   with:
      #     version: v3.14.4
      
      # - name: Login to GHCR
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${GITHUB_ACTOR}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push Helm chart to OCI compatible registry (Github)
        uses: bsord/helm-push@v4.2.0
        with:
          useOCIRegistry: true
          registry-url:  oci://ghcr.io/${{ github.repository }}
          username: ${GITHUB_ACTOR}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          chart-folder: charts
    
      # - name: Publish chart
      #   env:
      #     HELM_EXPERIMENTAL_OCI: '1'
      #     CHARTS_REPO: ghcr.io/${{ github.repository }}
      #     VERSION: ${{ github.ref_name }}
      #   run: |
      #     CHART_VERSION=$(echo $VERSION | cut -c 2-)
      #     cd charts/generic-app
      #     helm dep up
      #     helm package . --version ${CHART_VERSION} --app-version ${VERSION}
      #     helm push generic-app-${CHART_VERSION}.tgz oci://${CHARTS_REPO}

      # - name: Configure Git
      #   run: |
      #     git config user.name "$GITHUB_ACTOR"
      #     git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

        
      # - name: Run chart-releaser
      #   uses: helm/chart-releaser-action@main
      #   env:
      #     CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
